version: "3.9"

services:
  devtrack-api:
    build: .
    container_name: devtrack_api
    ports:
      - "3900:3900"
    environment:
      - PORT=3900
      - MONGO_URI=mongodb://mongo:27017/DEV_TRACKER
      - JWT_SECRET=${JWT_SECRET}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - CLIENT_URL=http://localhost:3900
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: devtrack_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: